name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: test
        with:
          keycloakUrl: https://test-keycloak.inkastle.studio/auth
          realm: Melterrea
          clientId: melterrea
          username: kcusername
          password: kcpassword

      - name: Check secret
        run: echo "${{steps.test.outputs.secret}}"
